UBUNTU: [Packaging] update helper scripts
BugLink: https://bugs.launchpad.net/bugs/1786013
Signed-off-by: Marcelo Henrique Cerri <marcelo.cerri@canonical.com>

diff --git a/debian/scripts/helpers/open b/debian/scripts/helpers/open
--- a/debian/scripts/helpers/open
+++ b/debian/scripts/helpers/open
@@ -175,8 +175,13 @@ if [ -d "$DEBIAN/abi" ]; then
 
 	if [ "$reuse_abi" -ne 0 ]; then
 		# Get the old ABI directory:
-		old=$(find "$DEBIAN/abi/" -mindepth 1 -maxdepth 1 -type d -a -name "${new%%-*}*")
-		if [ "$(echo "$old" | wc -l)" -gt 1 ]; then
+		old=$(find "$DEBIAN/abi/" -mindepth 1 -maxdepth 1 -type d | \
+				  grep -P '/abi/[0-9]+\.[0-9]+\.[0-9]+-[0-9]+\.[0-9]+')
+		if [ -z "${old}" ] ; then
+			echo "Failed to find the previous ABI directory." \
+				 "Please check \"$DEBIAN/abi/\"!" >&2
+			exit 1
+		elif [ "$(echo "$old" | wc -l)" -gt 1 ]; then
 			echo "Failed to rename the current ABI directory." \
 			     "Multiple directories found. Please check \"$DEBIAN/abi/\"!" >&2
 			exit 1
